theme: jekyll-theme-minimal
logo: https://user-images.githubusercontent.com/8364031/46570331-0c8f0180-c952-11e8-923d-536448190113.gif
/*logo: https://user-images.githubusercontent.com/8364031/46568767-2ae90300-c93a-11e8-9994-31e2b1e6841e.jpg*/
show_downloads: "true"
title: [![Travis-CI Build Status](https://travis-ci.org/magosil86/getspres.svg?branch=master)](https://travis-ci.org/magosil86/getspres)
description: [![GitHub license](https://img.shields.io/badge/license-MIT-blue.svg)](https://raw.githubusercontent.com/magosil86/getspres/master/LICENSE)


[![GitHub issues](https://img.shields.io/github/issues/magosil86/getspres.svg)](https://github.com/magosil86/getspres/issues)
[![CRAN_Status_Badge](http://www.r-pkg.org/badges/version/getspres)](https://cran.r-project.org/package=getspres)
[![CRAN_Logs_Rstudio](https://cranlogs.r-pkg.org/badges/grand-total/getspres)](http://cran.rstudio.com/web/packages/getspres/index.html)
