theme: jekyll-theme-minimal
logo: basket11_plus_magnifying_glass_for_web.gif
/*logo: https://user-images.githubusercontent.com/8364031/46568767-2ae90300-c93a-11e8-9994-31e2b1e6841e.jpg*/
show_downloads: "true"
